# Generated by Django 3.0.4 on 2020-04-16 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('bill_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('bill_type', models.CharField(default=None, max_length=10)),
                ('number', models.CharField(default=None, max_length=10)),
                ('term', models.CharField(default=None, max_length=6)),
                ('origin', models.CharField(default=None, max_length=10)),
                ('date_introduced', models.CharField(default=None, max_length=20)),
                ('sponsor_id', models.CharField(default=None, max_length=10)),
                ('policy_area', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
