# Generated by Django 3.0.4 on 2020-04-14 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandsCRP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cycle', models.CharField(max_length=7)),
                ('FECCandID', models.CharField(max_length=15)),
                ('CID', models.CharField(default=None, max_length=15)),
                ('FirstLastP', models.CharField(default=None, max_length=60)),
                ('Party', models.CharField(default=None, max_length=5)),
                ('DistIDRunFor', models.CharField(default=None, max_length=10)),
                ('DistIDCurr', models.CharField(default=None, max_length=10)),
                ('CurrCand', models.CharField(default=None, max_length=5)),
                ('CycleCand', models.CharField(default=None, max_length=3)),
                ('CRPICO', models.CharField(default=None, max_length=3)),
                ('RecipCode', models.CharField(default=None, max_length=5)),
                ('NoPacs', models.CharField(default=None, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Indivs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cycle', models.CharField(max_length=7)),
                ('FECTransID', models.CharField(max_length=28)),
                ('ContribID', models.CharField(default=None, max_length=20)),
                ('Contrib', models.CharField(default=None, max_length=70)),
                ('RecipID', models.CharField(default=None, max_length=20)),
                ('Orgname', models.CharField(default=None, max_length=70)),
                ('UltOrg', models.CharField(default=None, max_length=70)),
                ('RealCode', models.CharField(default=None, max_length=10)),
                ('Date', models.CharField(default=None, max_length=20)),
                ('Amount', models.CharField(default=None, max_length=20)),
                ('City', models.CharField(default=None, max_length=50)),
                ('State', models.CharField(default=None, max_length=5)),
                ('Zip', models.CharField(default=None, max_length=10)),
                ('Recipcode', models.CharField(default=None, max_length=5)),
                ('Type', models.CharField(default=None, max_length=6)),
                ('CmteID', models.CharField(default=None, max_length=15)),
                ('OtherID', models.CharField(default=None, max_length=16)),
                ('Gender', models.CharField(default=None, max_length=3)),
                ('Microfilm', models.CharField(default=None, max_length=20)),
                ('Occupation', models.CharField(default=None, max_length=50)),
                ('Employer', models.CharField(default=None, max_length=50)),
                ('Source', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PACs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cycle', models.CharField(max_length=7)),
                ('FECRecNo', models.CharField(max_length=25)),
                ('PACID', models.CharField(max_length=15)),
                ('CID', models.CharField(default=None, max_length=15)),
                ('Amount', models.CharField(default=0, max_length=30)),
                ('Date', models.CharField(default=None, max_length=30)),
                ('RealCode', models.CharField(default=None, max_length=10)),
                ('Type', models.CharField(default=None, max_length=6)),
                ('DI', models.CharField(default=None, max_length=5)),
                ('FECCandID', models.CharField(default=None, max_length=15)),
            ],
        ),
    ]
