# Generated by Django 3.0.3 on 2020-02-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('ID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Chamber', models.CharField(default=None, max_length=1)),
                ('CID', models.CharField(default=None, max_length=9)),
                ('CalendarYear', models.CharField(default=None, max_length=2)),
                ('ReportType', models.CharField(default=None, max_length=1)),
                ('CompSource', models.CharField(default=None, max_length=100)),
                ('Orgname', models.CharField(default=None, max_length=40)),
                ('Ultorg', models.CharField(default=None, max_length=40)),
                ('Realcode', models.CharField(default=None, max_length=5)),
                ('Source', models.CharField(default=None, max_length=5)),
                ('CompSourceLocation', models.CharField(default=None, max_length=50)),
                ('CompDuties', models.CharField(default=None, max_length=100)),
                ('dupe', models.CharField(default=None, max_length=1)),
            ],
        ),
    ]
